// City and search term lists for Google Maps discovery

const TIER1_TERMS = [
  'LGBTQ friendly store',
  'queer owned shop',
  'inclusive boutique',
  'gender affirming clothing',
  'pride shop',
  'queer boutique',
];

const TIER2_TERMS = [
  'bra fitting',
  'lingerie boutique',
  'independent underwear store',
  'intimate apparel',
  'adult store',
  'sex shop',
  "women's boutique",
  'body positive clothing',
  'swimwear boutique',
];

// 50 high-LGBTQ-population US cities (with state for unambiguous API queries)
const TIER1_CITIES = [
  'New York City NY',
  'Los Angeles CA',
  'San Francisco CA',
  'Chicago IL',
  'Seattle WA',
  'Portland OR',
  'Minneapolis MN',
  'Denver CO',
  'Austin TX',
  'Atlanta GA',
  'Boston MA',
  'Philadelphia PA',
  'Washington DC',
  'Miami FL',
  'San Diego CA',
  'Oakland CA',
  'New Orleans LA',
  'Nashville TN',
  'Phoenix AZ',
  'Dallas TX',
  'Houston TX',
  'Columbus OH',
  'Pittsburgh PA',
  'Salt Lake City UT',
  'Asheville NC',
  'Providence RI',
  'Burlington VT',
  'Northampton MA',
  'Palm Springs CA',
  'Provincetown MA',
  'Wilton Manors FL',
  'Asbury Park NJ',
  'Rehoboth Beach DE',
  'Eureka Springs AR',
  'Guerneville CA',
  'Orlando FL',
  'Tampa FL',
  'Albuquerque NM',
  'Tucson AZ',
  'Sacramento CA',
  'Raleigh-Durham NC',
  'Charlotte NC',
  'Indianapolis IN',
  'Milwaukee WI',
  'St. Louis MO',
  'Kansas City MO',
  'Richmond VA',
  'Baltimore MD',
  'Detroit MI',
  'Cleveland OH',
];

// 53 progressive small/mid cities + college towns
const TIER2_CITIES = [
  'Asheville NC',
  'Bend OR',
  'Burlington VT',
  'Northampton MA',
  'Ithaca NY',
  'Ann Arbor MI',
  'Madison WI',
  'Iowa City IA',
  'Eugene OR',
  'Olympia WA',
  'Santa Fe NM',
  'Taos NM',
  'Sedona AZ',
  'Key West FL',
  'Savannah GA',
  'Charleston SC',
  'Woodstock NY',
  'New Hope PA',
  'Saugerties NY',
  'Brattleboro VT',
  'Montpelier VT',
  'Easthampton MA',
  'Hudson NY',
  'Beacon NY',
  'Red Bank NJ',
  'Lambertville NJ',
  'Takoma Park MD',
  'Yellow Springs OH',
  'Berea KY',
  'Hot Springs AR',
  'Marfa TX',
  'Joshua Tree CA',
  'Ojai CA',
  'Sebastopol CA',
  'Petaluma CA',
  'Boulder CO',
  'Chapel Hill NC',
  'Amherst MA',
  'Oberlin OH',
  'Missoula MT',
  'Charlottesville VA',
  'Ashland OR',
  'Bloomington IN',
  'Lawrence KS',
  'Corvallis OR',
  'Gainesville FL',
  'Athens GA',
  'Davis CA',
  'San Luis Obispo CA',
  'Flagstaff AZ',
  'Duluth MN',
  'Bozeman MT',
  'Bellingham WA',
];

module.exports = { TIER1_TERMS, TIER2_TERMS, TIER1_CITIES, TIER2_CITIES };
