/**
 * Publish active donation partners to the rubies-ecom-v4 theme repo as a
 * static JSON asset.
 *
 * The theme's donation page (page.donate-preloved) reads this file at build
 * time. Updates are infrequent and intentional, so no live fetch.
 *
 * Output contract (matches what the theme consumes):
 *   { name, address, description, sizeRange, imageUrl, orgUrl, lat, lng }
 *
 * Worktree/PR/merge mechanics live in themeAssetPublish.js (shared with the
 * store locator publisher). This module is callable from both the MCP tool
 * and the CLI.
 */

const path = require('path');

const { getSupabaseClient } = require('../../shared/supabaseClient');
const { publishThemeAsset } = require('./themeAssetPublish');
const { formatSizeAcceptance } = require('./sizeAcceptance');

const DEFAULT_THEME_ASSET_PATH = path.resolve(
  __dirname, '../../../rubies-ecom-v4/assets/donation-partners.json'
);

const LIVE_PAGE_URL = 'https://rubyshines.com/pages/donate-your-pre-loved-rubies-clothing';

function toPublicShape(row) {
  return {
    name: row.name,
    address: row.mailing_address || row.address || '',
    description: row.description || '',
    // Derived, never stored — so the sizes a shopper reads on the donation page
    // are the same ones routing actually filters on.
    sizeRange: formatSizeAcceptance(row),
    imageUrl: row.logo_url || '',
    orgUrl: row.website_url || '',
    lat: Number(row.latitude),
    lng: Number(row.longitude),
  };
}

async function readActivePartners() {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from('donation_partners')
    .select('name, mailing_address, address, description, accepts_smaller_sizes, accepts_larger_sizes, logo_url, website_url, latitude, longitude, active')
    .eq('active', true)
    .order('country_code')
    .order('name');

  if (error) throw new Error(`Failed to read donation_partners: ${error.message}`);

  const issues = [];
  for (const row of data) {
    if (!Number.isFinite(Number(row.latitude)) || !Number.isFinite(Number(row.longitude))) {
      issues.push(`${row.name}: missing/invalid lat/lng`);
    }
    if (!row.logo_url) issues.push(`${row.name}: missing logo_url`);
    if (!row.mailing_address && !row.address) issues.push(`${row.name}: missing mailing_address and address`);
  }
  if (issues.length) {
    throw new Error(`Cannot publish — ${issues.length} partner(s) missing required fields:\n  - ${issues.join('\n  - ')}`);
  }
  return data.map(toPublicShape);
}

/**
 * @param {object} opts
 *   outPath     where to write the JSON (default = theme repo working tree)
 *   dry_run     true → only write the working tree, no commit/push/merge
 *   merge       true (default) → also open PR + squash-merge → auto-deploys
 *               false → just commit + push to a branch, leave merge to operator
 *   baseBranch  default 'main'
 */
async function publishDonationPartners({
  outPath = DEFAULT_THEME_ASSET_PATH,
  dry_run = false,
  merge = true,
  baseBranch = 'main',
} = {}) {
  const payload = await readActivePartners();

  return publishThemeAsset(payload, {
    outPath,
    dry_run,
    merge,
    baseBranch,
    liveUrl: LIVE_PAGE_URL,
    relativeOutPath: path.join('assets', 'donation-partners.json'),
    branchPrefix: 'data/donation-partners',
    commitTitle: `data: update donation-partners.json (${payload.length} active partners)`,
    commitBody: 'Generated from rubies-automations donation_partners table.\nSource of truth: customer-service/lib/donationPartnersPublish.js',
    prTitle: `data: donation partners (${payload.length} active)`,
    prBody: 'Auto-generated by rubies-automations donation_partner_publish.\n\nThis PR updates assets/donation-partners.json. Merged automatically as part of the publish flow.',
  });
}

module.exports = { publishDonationPartners, DEFAULT_THEME_ASSET_PATH, LIVE_PAGE_URL };
