/**
 * Publish active store locator entries to the rubies-ecom-v4 theme repo as a
 * static JSON asset.
 *
 * Reads b2b_companies WHERE on_store_locator = true (sorted by id for
 * deterministic output) and writes rubies-ecom-v4/assets/store-locators.json.
 *
 * Output contract (matches what the theme section consumes):
 *   { name, address, description, hours, products, imageUrl, storeUrl, lat, lng }
 *
 * Worktree/PR/merge mechanics live in themeAssetPublish.js (shared with the
 * donation partners publisher). This module is callable from both the MCP
 * tool and the CLI.
 */

const path = require('path');

const { getSupabaseClient } = require('../../shared/supabaseClient');
const { publishThemeAsset } = require('./themeAssetPublish');

const DEFAULT_THEME_ASSET_PATH = path.resolve(
  __dirname, '../../../rubies-ecom-v4/assets/store-locators.json'
);

const LIVE_PAGE_URL = 'https://rubyshines.com/pages/store-locator';

function toPublicShape(row) {
  let storeUrl = row.website || '';
  if (storeUrl && !/^https?:\/\//i.test(storeUrl)) storeUrl = 'https://' + storeUrl;
  return {
    name: row.locator_display_name || row.name,
    address: row.locator_display_address || '',
    description: row.locator_description || '',
    hours: row.locator_hours || '',
    products: row.locator_products || ['swimwear', 'underwear'],
    imageUrl: row.locator_logo_url || '',
    storeUrl,
    lat: Number(row.latitude),
    lng: Number(row.longitude),
  };
}

async function readActiveStores() {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from('b2b_companies')
    .select('id, name, website, locator_display_name, locator_display_address, locator_description, locator_hours, locator_products, locator_logo_url, latitude, longitude')
    .eq('on_store_locator', true)
    .order('id');

  if (error) throw new Error(`Failed to read b2b_companies: ${error.message}`);

  const issues = [];
  for (const row of data) {
    const lat = Number(row.latitude);
    const lng = Number(row.longitude);
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
      issues.push(`${row.name}: missing/invalid lat/lng`);
    }
  }
  if (issues.length) {
    throw new Error(`Cannot publish — ${issues.length} store(s) missing required fields:\n  - ${issues.join('\n  - ')}`);
  }

  return data.map(toPublicShape);
}

/**
 * @param {object} opts
 *   outPath     where to write the JSON (default = theme repo working tree)
 *   dry_run     true → only write the working tree, no commit/push/merge
 *   merge       true (default) → open PR + squash-merge → auto-deploys
 *               false → commit + push to branch, leave merge to operator
 *   baseBranch  default 'main'
 */
async function publishStoreLocators({
  outPath = DEFAULT_THEME_ASSET_PATH,
  dry_run = false,
  merge = true,
  baseBranch = 'main',
} = {}) {
  const payload = await readActiveStores();

  return publishThemeAsset(payload, {
    outPath,
    dry_run,
    merge,
    baseBranch,
    liveUrl: LIVE_PAGE_URL,
    relativeOutPath: path.join('assets', 'store-locators.json'),
    branchPrefix: 'data/store-locators',
    commitTitle: `data: update store-locators.json (${payload.length} active stores)`,
    commitBody: 'Generated from rubies-automations b2b_companies table.\nSource of truth: customer-service/lib/storeLocatorPublish.js',
    prTitle: `data: store locators (${payload.length} active)`,
    prBody: 'Auto-generated by rubies-automations store_locator_publish.\n\nThis PR updates assets/store-locators.json. Merged automatically as part of the publish flow.',
  });
}

module.exports = { publishStoreLocators, DEFAULT_THEME_ASSET_PATH, LIVE_PAGE_URL };
