/**
 * Publish active store locator entries to the rubies-ecom-v4 theme repo as a
 * static JSON asset.
 *
 * Reads b2b_companies WHERE on_store_locator = true (sorted by id for
 * deterministic output) and writes rubies-ecom-v4/assets/store-locators.json.
 * Auto-merges to main via a temporary git worktree so any in-progress theme
 * branch is left untouched.
 *
 * Output contract (matches what the theme section consumes):
 *   { name, address, description, hours, products, imageUrl, storeUrl, lat, lng }
 *
 * This module is callable from both the MCP tool and the CLI.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const { getSupabaseClient } = require('../../shared/supabaseClient');

const DEFAULT_THEME_ASSET_PATH = path.resolve(
  __dirname, '../../../rubies-ecom-v4/assets/store-locators.json'
);

const LIVE_PAGE_URL = 'https://rubyshines.com/pages/store-locator';

function toPublicShape(row) {
  let storeUrl = row.website || '';
  if (storeUrl && !/^https?:\/\//i.test(storeUrl)) storeUrl = 'https://' + storeUrl;
  return {
    name: row.locator_display_name || row.name,
    address: row.locator_display_address || '',
    description: row.locator_description || '',
    hours: row.locator_hours || '',
    products: row.locator_products || ['swimwear', 'underwear'],
    imageUrl: row.locator_logo_url || '',
    storeUrl,
    lat: Number(row.latitude),
    lng: Number(row.longitude),
  };
}

async function readActiveStores() {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from('b2b_companies')
    .select('id, name, website, locator_display_name, locator_display_address, locator_description, locator_hours, locator_products, locator_logo_url, latitude, longitude')
    .eq('on_store_locator', true)
    .order('id');

  if (error) throw new Error(`Failed to read b2b_companies: ${error.message}`);

  const issues = [];
  for (const row of data) {
    const lat = Number(row.latitude);
    const lng = Number(row.longitude);
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
      issues.push(`${row.name}: missing/invalid lat/lng`);
    }
  }
  if (issues.length) {
    throw new Error(`Cannot publish — ${issues.length} store(s) missing required fields:\n  - ${issues.join('\n  - ')}`);
  }

  return data.map(toPublicShape);
}

function serializePayload(payload) {
  return JSON.stringify(payload, null, 2) + '\n';
}

function gitc(cwd, args) {
  return execFileSync('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
}

function ghc(cwd, args) {
  return execFileSync('gh', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
}

async function publishViaWorktree(payload, { themeRepo, baseBranch = 'main', merge = true }) {
  if (!fs.existsSync(path.join(themeRepo, '.git'))) {
    throw new Error(`Not a git repo: ${themeRepo}`);
  }
  const remoteUrl = gitc(themeRepo, ['remote', 'get-url', 'origin']);

  gitc(themeRepo, ['fetch', 'origin', baseBranch]);

  const stamp = new Date().toISOString().slice(0, 16).replace(/[-:T]/g, '');
  const branch = `data/store-locators-${stamp}`;
  const wt = path.join(os.tmpdir(), `rubies-theme-store-locator-${stamp}-${process.pid}`);

  gitc(themeRepo, ['worktree', 'add', '-b', branch, wt, `origin/${baseBranch}`]);

  try {
    const relativeOutPath = path.join('assets', 'store-locators.json');
    const outAbsPath = path.join(wt, relativeOutPath);
    fs.writeFileSync(outAbsPath, serializePayload(payload), 'utf8');

    const status = gitc(wt, ['status', '--porcelain']);
    if (!status) {
      gitc(themeRepo, ['worktree', 'remove', '--force', wt]);
      try { gitc(themeRepo, ['branch', '-D', branch]); } catch { /* no-op */ }
      return { branch: null, baseBranch, themeRepo, remoteUrl, noOp: true };
    }

    gitc(wt, ['add', relativeOutPath]);
    gitc(wt, [
      'commit',
      '-m', `data: update store-locators.json (${payload.length} active stores)`,
      '-m', 'Generated from rubies-automations b2b_companies table.\nSource of truth: customer-service/lib/storeLocatorPublish.js',
    ]);
    gitc(wt, ['push', '-u', 'origin', branch]);

    if (!merge) {
      return { branch, baseBranch, themeRepo, remoteUrl, merged: false };
    }

    let prUrl;
    try {
      prUrl = ghc(wt, [
        'pr', 'create',
        '--base', baseBranch,
        '--head', branch,
        '--title', `data: store locators (${payload.length} active)`,
        '--body', 'Auto-generated by rubies-automations store_locator_publish.\n\nThis PR updates assets/store-locators.json. Merged automatically as part of the publish flow.',
      ]);
    } catch (e) {
      return { branch, baseBranch, themeRepo, remoteUrl, merged: false, mergeError: `pr create failed: ${e.message}` };
    }

    let mergeWarning = null;
    try {
      ghc(wt, ['pr', 'merge', prUrl, '--squash', '--delete-branch']);
    } catch (e) {
      try {
        const state = ghc(wt, ['pr', 'view', prUrl, '--json', 'state,mergedAt']);
        const parsed = JSON.parse(state);
        if (parsed.state === 'MERGED') {
          mergeWarning = `Merge succeeded but local cleanup hit a non-fatal error: ${e.message.split('\n').pop()}`;
        } else {
          return { branch, baseBranch, themeRepo, remoteUrl, merged: false, prUrl, mergeError: `pr merge failed (state=${parsed.state}): ${e.message}` };
        }
      } catch (verifyErr) {
        return { branch, baseBranch, themeRepo, remoteUrl, merged: false, prUrl, mergeError: `pr merge failed and state-check also failed: ${e.message}` };
      }
    }

    // Clean up the local branch — it now lives on the remote (merged) and we
    // don't need a local ref. gh pr merge --delete-branch tries this too but
    // fails non-fatally when the worktree is still around; do it explicitly.
    try { gitc(themeRepo, ['branch', '-D', branch]); } catch { /* swallow */ }
    return { branch, baseBranch, themeRepo, remoteUrl, merged: true, prUrl, mergeWarning };
  } finally {
    try { gitc(themeRepo, ['worktree', 'remove', '--force', wt]); } catch { /* swallow */ }
  }
}

/**
 * @param {object} opts
 *   outPath     where to write the JSON (default = theme repo working tree)
 *   dry_run     true → only write the working tree, no commit/push/merge
 *   merge       true (default) → open PR + squash-merge → auto-deploys
 *               false → commit + push to branch, leave merge to operator
 *   baseBranch  default 'main'
 */
async function publishStoreLocators({
  outPath = DEFAULT_THEME_ASSET_PATH,
  dry_run = false,
  merge = true,
  baseBranch = 'main',
} = {}) {
  const payload = await readActiveStores();

  const outDir = path.dirname(outPath);
  if (!fs.existsSync(outDir)) {
    throw new Error(`Theme assets dir does not exist: ${outDir} (is rubies-ecom-v4 checked out as a sibling of rubies-automations?)`);
  }

  fs.writeFileSync(outPath, serializePayload(payload), 'utf8');

  if (dry_run) {
    return { path: outPath, count: payload.length, committed: false, dryRun: true };
  }

  const themeRepo = path.dirname(outDir);
  const wt = await publishViaWorktree(payload, { themeRepo, baseBranch, merge });
  return {
    path: outPath,
    count: payload.length,
    committed: !wt.noOp,
    merged: !!wt.merged,
    noOp: !!wt.noOp,
    branch: wt.branch,
    baseBranch: wt.baseBranch,
    themeRepo: wt.themeRepo,
    remoteUrl: wt.remoteUrl,
    prUrl: wt.prUrl,
    mergeError: wt.mergeError,
    mergeWarning: wt.mergeWarning,
    liveUrl: LIVE_PAGE_URL,
  };
}

module.exports = { publishStoreLocators, DEFAULT_THEME_ASSET_PATH, LIVE_PAGE_URL };
