/**
 * replyCorrelation.js — Trigger 2: inbound email → B2B relationship state.
 *
 * Called from the Gmail push handler (and the nightly sync as catch-up) for
 * each new inbound message. If the sender belongs to a known B2B contact or a
 * company's general_email, the message is recorded on the company's thread
 * (idempotent on gmail_message_id — Pub/Sub is at-least-once) and the company
 * surfaces as Tier 1 in the queue (computed from lastInbound > lastOutbound).
 *
 * Also implements the design's contact-change detection: hard bounces and
 * "no longer with" auto-replies flag contact_unknown, which pauses cadence
 * (cadence.companyEligible) until the operator confirms a new contact.
 */
const { isSystemMailbox } = require('./emailDomains');
const { getSupabaseClient } = require('../../shared/supabaseClient');
const { resolveCompanyForAddress } = require('./companyMatch');
const { parseBounce, handleBounce } = require('./bounceRecovery');

/** Bounce / departure detection (Design #3 contact-change flow). Pure. */
function detectContactLoss({ subject = '', body = '', from = '' } = {}) {
  const s = `${subject}\n${body}`.slice(0, 2000);
  if (/mailer-daemon|postmaster@/i.test(from) && /(delivery|undeliver|not be delivered|address not found|550|user unknown)/i.test(s)) {
    return 'hard_bounce';
  }
  if (/(no longer (with|at|works)|has left the (org|company|team)|is no longer employed|please (contact|reach out to) .{0,60} going forward)/i.test(s)) {
    return 'departed';
  }
  return null;
}

/** Heuristic: does an inbound look like a wholesale order? Pure. */
function looksLikeOrder(body = '') {
  const lines = body.split('\n');
  let itemish = 0;
  for (const l of lines) {
    if (/^\s*\d+\s*[xX×]?\s+[A-Za-z]/.test(l) && /(size|S|M|L|XL|\d{1,2})/i.test(l)) itemish++;
  }
  return itemish >= 2 || /\b(purchase order|PO\s*#|wholesale order|order form)\b/i.test(body);
}

/**
 * Conservative auto-responder detection (content layer — the gmail intake's
 * is_auto_reply and protocol headers are the first line; this catches what
 * they miss, e.g. Mermaids' "we'll be back to you within 2 business days").
 * Deliberately narrow patterns: a mislabel in either direction is visible and
 * recoverable (the message stays in history either way), so favor precision.
 * Pure.
 */
const AUTO_REPLY_PATTERN = /\b(automatic reply|auto[- ]?repl(y|ied)|out of (the )?office|this (inbox|mailbox) is not monitored|do not reply to this (e-?mail|message)|we('|’)?ll (get|be) back to you within [^.\n]{0,30}(business |working )?days)\b/i;

function detectAutoReply({ subject, body }) {
  const s = String(subject || '');
  const b = String(body || '');
  // A subject that OPENS with "Re:" is a person writing into an existing
  // thread — including into an auto-responder's own thread, which Gmail gives
  // its own subject ("Out of Office Re: ..."). Judging that on the subject
  // would file their reply as machine-generated, and since such a thread is
  // now born closed, the reply would be invisible twice over. So judge it on
  // the body alone: a genuine responder announces itself there too. Same
  // reasoning detectCalendarNotice already applies to "Re: Accepted: ...".
  if (/^\s*re:\s*/i.test(s)) return AUTO_REPLY_PATTERN.test(b);
  return AUTO_REPLY_PATTERN.test(`${s}\n${b}`);
}

/**
 * Calendar notifications: an RSVP, an invitation, an update, a cancellation.
 *
 * These are generated by calendar software but sent FROM the contact's own
 * address, so every layer above treats them as that person writing to us. An
 * acceptance in particular lands AFTER our last outbound (we send the invite,
 * they accept), which is exactly the Tier-1 condition — so booking a call puts
 * the company straight back in the queue as "replied, waiting on us" at the
 * moment the scheduling is finished and there is least to say. Lumenus was
 * queued by an acceptance of a call that was already booked, and the only way
 * to clear it was to close the notification by hand.
 *
 * Held to the same precision-first bar as detectAutoReply: the message stays in
 * history either way, but a false positive here silences a real human.
 * Pure.
 */
const CALENDAR_SUBJECT = /^\s*(accepted|declined|tentative|invitation|updated invitation|new event|updated event|cancell?ed event|canceled event):\s+\S/i;
const CALENDAR_RSVP = /^\s*(accepted|declined|tentative):\s+\S/i;
const CALENDAR_BODY = /(calendar\.google\.com\/calendar\/event|has (accepted|declined|tentatively accepted) this invitation|this event has been (updated|cancell?ed|canceled)|BEGIN:VCALENDAR)/i;

function detectCalendarNotice({ subject, body } = {}) {
  const s = String(subject || '');
  // No `Re:` tolerance anywhere here, deliberately. A generated notice never
  // carries one, and Gmail threads on subject — so a human replying inside the
  // notification's thread arrives as "Re: Accepted: …" and must stay a reply.
  if (!CALENDAR_SUBJECT.test(s)) return false;
  // An RSVP subject is unambiguous: nobody writes "Accepted: <thing>" as an
  // entire subject line. It also has to stand on the subject alone — the RSVP
  // is the one that reaches correlateInbound with an EMPTY body over Pub/Sub,
  // so requiring corroboration would miss the case this exists for.
  if (CALENDAR_RSVP.test(s)) return true;
  // "Invitation: Pride Picnic 2026" is a subject an org could plausibly write
  // by hand, so this half has to be corroborated by the body.
  const b = String(body || '').trim();
  return !b || CALENDAR_BODY.test(b);
}

/**
 * Inbound message_types that are on the record but are not a person waiting on
 * a reply. queueContext skips these when deriving lastInboundAt, which is what
 * keeps them out of Tier 1.
 */
// A delivery failure joins these for the same reason a calendar acceptance
// does: it is evidence ABOUT a message, never a human writing back. The DSN is
// kept on the thread so the panel can show why a check-in got no answer, but
// counting it as a reply would put the company at Tier 1 as though they had
// replied — which is exactly what the pre-fix panel did.
const NON_REPLY_INBOUND_TYPES = new Set(['auto_reply', 'calendar_notice', 'bounce']);

/**
 * Classify an inbound message. Returns a message_type or null. Pure.
 *
 * `headerAutoReply` is the Gmail intake's verdict from protocol headers
 * (Auto-Submitted, X-Autoreply, Precedence). It is the first line of
 * detection and the content patterns below are what catch the responders
 * that skip the headers — so a header hit is honoured even when the body
 * says nothing recognisable. Bounce and calendar checks still run first:
 * a DSN is also header-flagged and must land on its own, sharper branch.
 */
function classifyInbound({ subject, body, from, headerAutoReply = false, calendarMethod = null } = {}) {
  if (detectContactLoss({ subject, body, from }) === 'hard_bounce') return 'bounce';
  // `calendarMethod` is the iCalendar METHOD the Gmail intake read off a
  // text/calendar MIME part (REQUEST, REPLY, CANCEL). Language-independent
  // where the subject test is not: a French Outlook RSVP arrives as
  // "Acceptée : …" with an empty body, and the English subject regex filed it
  // as a person waiting on us in Tier 1.
  if (calendarMethod || detectCalendarNotice({ subject, body })) return 'calendar_notice';
  if (headerAutoReply || detectAutoReply({ subject, body })) return 'auto_reply';
  return null;
}

/**
 * Correlate one inbound message. Returns
 * { matched, company_id?, thread_id?, duplicate?, contact_loss?, looks_like_order?, auto_reply? }.
 */
async function correlateInbound(msg) {
  const { gmail_message_id, gmail_thread_id, from_email, to_email, cc_email, subject, body_text, received_at, is_auto_reply, calendar_method } = msg;
  if (!gmail_message_id || !from_email) return { matched: false, reason: 'missing ids' };
  const sb = getSupabaseClient();
  const sender = String(from_email).toLowerCase().replace(/^.*</, '').replace(/>.*$/, '').trim();

  // 1. Sender → company. Exact contact, then general_email, then the sender's
  // identifying DOMAIN (16 of 45 uncorrelated threads were companies we already
  // knew, writing from an unregistered colleague's address). The resolution
  // lives in companyMatch.js and is shared with the calendar meeting sync, so
  // an email sender and a calendar attendee can never resolve differently.
  // When the domain path matches, the address is registered below so the
  // exact match wins next time.
  const match = await resolveCompanyForAddress(sb, sender);
  let companyId = match.company_id;
  const matchedByDomain = match.matched_by === 'domain_website' || match.matched_by === 'domain_peer';

  // Bounce case: the sender is mailer-daemon, so it tells us nothing about who
  // this is about. The DSN's Final-Recipient does — and it is a far sharper key
  // than the thread, which Gmail shares between orgs: naming the failed address
  // says exactly whose contact died, where an ambiguous thread previously had to
  // give up rather than risk pausing the wrong org's cadence.
  const loss = detectContactLoss({ subject, body: body_text, from: sender });
  const parsedBounce = loss === 'hard_bounce'
    ? parseBounce({ subject, body: body_text, from: sender }) : null;
  if (!companyId && parsedBounce) {
    for (const f of parsedBounce.failures) {
      const { data: c } = await sb.from('b2b_contacts')
        .select('company_id').eq('email', f.address).maybeSingle();
      if (c?.company_id) { companyId = c.company_id; break; }
      const { data: m } = await sb.from('b2b_messages')
        .select('company_id').eq('to_email', f.address).eq('direction', 'outbound')
        .order('sent_at', { ascending: false }).limit(1);
      if (m?.[0]?.company_id) { companyId = m[0].company_id; break; }
    }
  }
  if (!companyId && loss === 'hard_bounce' && gmail_thread_id) {
    // Fallback for a DSN we could not read a recipient out of. Still refuses to
    // guess on a shared thread: marking the wrong org's contact dead pauses a
    // relationship that was perfectly healthy.
    const { data: threads } = await sb.from('b2b_threads')
      .select('company_id').eq('gmail_thread_id', gmail_thread_id);
    const owners = [...new Set((threads || []).map(t => t.company_id))];
    if (owners.length === 1) companyId = owners[0];
  }
  if (!companyId) {
    // A bounce we cannot attribute is a dead address we will keep writing to.
    if (loss === 'hard_bounce') {
      console.warn(`[correlate] unattributed bounce ${gmail_message_id}: ${(parsedBounce?.failures || []).map(f => f.address).join(', ') || 'no recipient parsed'}`);
    }
    return { matched: false, contact_loss: loss || undefined };
  }

  // 2. Thread: match by (company, gmail_thread_id), else create.
  //
  // Scoped by company, not by gmail_thread_id alone. Gmail threads on subject, so
  // one conversation regularly holds two orgs — an unscoped lookup found the OTHER
  // company's row and filed this message under their relationship. That is how 105
  // messages ended up mis-parented. A company now only ever matches its own row.
  const inboundType = classifyInbound({
    subject, body: body_text, from: sender, headerAutoReply: !!is_auto_reply, calendarMethod: calendar_method || null,
  });

  let threadId = null;
  let threadWasNew = false;
  let threadStatus = 'open';
  const { data: thread } = await sb.from('b2b_threads')
    .select('id, status').eq('gmail_thread_id', gmail_thread_id).eq('company_id', companyId).maybeSingle();
  if (thread) {
    threadId = thread.id;
    threadStatus = thread.status || 'open';
  } else {
    threadWasNew = true;
    // A thread whose FIRST message is machine-generated is born concluded.
    // Gmail threads on subject, so an out-of-office ("Out of office RE: ...")
    // opens a thread of its own, and there is nothing for a person to do with
    // it. discoveredThreadStatus has always applied this rule on the Gmail
    // discovery path; live Pub/Sub inbound never did, so every auto-reply that
    // arrived in real time left an open thread to be closed by hand.
    //
    // Only ever at CREATION. An auto-reply landing inside a live conversation
    // must not close it — they are still mid-thread with us, and the responder
    // says nothing about that.
    const bornClosed = NON_REPLY_INBOUND_TYPES.has(inboundType);
    const { data: created, error } = await sb.from('b2b_threads').insert({
      company_id: companyId, thread_type: 'other',
      subject: (subject || '').slice(0, 300), gmail_thread_id,
      last_message_at: received_at || new Date().toISOString(),
      ...(bornClosed ? { status: 'closed' } : {}),
    }).select('id').single();
    if (error) {
      // unique race: another worker created it — refetch
      const { data: again } = await sb.from('b2b_threads')
        .select('id').eq('gmail_thread_id', gmail_thread_id).eq('company_id', companyId).maybeSingle();
      if (!again) throw new Error(`thread create: ${error.message}`);
      threadId = again.id;
    } else {
      threadId = created.id;
    }
  }

  // 3. Idempotent message insert (UNIQUE gmail_message_id). Auto-responders,
  // calendar notifications and delivery failures are kept for history but
  // labeled so they never create a Tier-1 "waiting on us" (queueContext skips
  // the types in NON_REPLY_INBOUND_TYPES). Keeping the DSN matters: without it
  // the panel shows a warm check-in going out and silence coming back, which is
  // exactly how two dead partner addresses stayed invisible.
  const { error: mErr } = await sb.from('b2b_messages').insert({
    thread_id: threadId, company_id: companyId, direction: 'inbound',
    message_type: inboundType,
    gmail_message_id, gmail_thread_id,
    from_email: sender, to_email: to_email || null, cc_email: cc_email || null,
    body_text: (body_text || '').slice(0, 20000),
    sent_at: received_at || new Date().toISOString(), source: 'pubsub',
  });
  let duplicate = false;
  if (mErr) {
    if (mErr.code !== '23505') throw new Error(`b2b_messages insert: ${mErr.message}`);
    // Already stored — which says nothing about whether its CONSEQUENCES were
    // applied. Returning here skipped bounce handling for exactly the messages
    // the replay exists to repair (it re-reads mail the push path already
    // inserted), and still reported a match, so a run that did nothing looked
    // like a run that worked. handleBounce is independently idempotent; let it
    // be the thing that decides whether there is work left.
    duplicate = true;
  }

  // 3b. Register an address we only reached via the domain fallback, so the
  // exact-address match handles it next time and resolveRecipient can see it.
  // Not primary: a colleague writing in does not displace the person we have
  // deliberately been corresponding with.
  // Never a system mailbox: a bounce DSN comes from postmaster@ at the
  // company's own domain, which matches by domain like any colleague would.
  if (matchedByDomain && !isSystemMailbox(sender)) {
    const { error: cErr } = await sb.from('b2b_contacts').upsert({
      id: sender, email: sender, company_id: companyId,
      is_primary: false, is_active: true, source: 'inbound_domain_match',
      notes: `Auto-added ${new Date().toISOString().slice(0, 10)}: wrote in from a domain already on this company.`,
    }, { onConflict: 'id', ignoreDuplicates: true });
    if (cErr) console.warn(`[correlate] contact auto-add ${sender}: ${cErr.message}`);
  }

  // 4. State updates
  const nowIso = new Date().toISOString();
  await sb.from('b2b_threads').update({ last_message_at: received_at || nowIso }).eq('id', threadId);
  // A person writing into a CLOSED thread reopens it (2026-09-11). Closing is
  // the operator saying "nothing more to say until they come back" — and this
  // is them coming back. Every other deferral already holds the rule that a
  // reply arriving after it was set always surfaces; close was the one that
  // did not, so a hand-off and a new coordinator's reply sat on a closed
  // thread invisible to Tier 1, and the read-state sweep then un-bolded them
  // in Gmail because "thread closed" reads as "nobody waiting". Only on the
  // FIRST delivery of the message: the nightly replay re-reads stored mail,
  // and reopening on a redelivery would undo a close the operator made after
  // reading this very reply. Never for machine mail — an out-of-office says
  // nothing about whether the conversation is live. The thank-you closer runs
  // after this and may close it straight back if the reply is a bare "thanks".
  let reopened = false;
  if (inboundType === null && !duplicate && !threadWasNew && threadStatus === 'closed') {
    const { data: flipped, error: rErr } = await sb.from('b2b_threads')
      .update({ status: 'open' }).eq('id', threadId).eq('status', 'closed').select('id');
    if (rErr) console.warn(`[correlate] reopen thread ${threadId}: ${rErr.message}`);
    else if (flipped?.length) {
      reopened = true;
      console.log(`[correlate] thread ${threadId} reopened on ${companyId}: ${sender} wrote into a closed conversation`);
    }
  }
  // A genuine human reply makes any waiting initiating draft (cold intro,
  // check-in, re-approach, reorder nudge) obsolete: the conversation is now
  // live, and live conversations are operator-written (2026-09-02). Runs even
  // on a duplicate insert — a record already existing says nothing about
  // whether its consequences were applied, and the update is idempotent.
  // Scheduled ladder drafts are left alone: their own send-time reply re-check
  // holds them, and dismissing here would race it.
  if (inboundType === null) {
    const { INITIATING_TYPES } = require('./cadence');
    const { data: dismissed, error: dErr } = await sb.from('b2b_drafts')
      .update({ status: 'dismissed' })
      .eq('company_id', companyId).eq('status', 'pending')
      .in('message_type', INITIATING_TYPES).is('scheduled_send_at', null)
      .select('id, message_type');
    if (dErr) console.warn(`[correlate] initiating-draft dismiss ${companyId}: ${dErr.message}`);
    else for (const d of dismissed || []) console.log(`[correlate] dismissed initiating draft #${d.id} (${d.message_type}) on ${companyId}: they wrote in`);
  }
  // A hard bounce knows WHICH address died, so it can do the specific thing:
  // retire that contact, revive the approved text against a live one, and undo
  // the cadence date the failed send bought. Flagging the whole company
  // `contact_unknown` here instead would pause it entirely and render nowhere —
  // muting a partner we can still reach at another address.
  let bounce = null;
  if (parsedBounce) {
    for (const failure of parsedBounce.failures) {
      if (!failure.permanent) continue;
      bounce = await handleBounce(sb, { failure, gmail_thread_id, now: new Date(nowIso) });
    }
    if (parsedBounce.unparsed) {
      console.warn(`[correlate] unreadable DSN ${gmail_message_id} on company ${companyId}`);
    }
  }
  // A departure notice is a bounce's sibling that names where to write instead.
  // departureRecovery reads the successor out of it, moves the contact, marks
  // the answered send undelivered and schedules the retry; when the notice
  // names nobody usable it leaves the company at Tier 1 "no working address"
  // with a reason that says who left. Runs on a duplicate insert too — the
  // replay re-reads mail the push path already stored, and handleDeparture is
  // idempotent on the send's undelivered_at. Fail-soft: a failure here must
  // not undo the correlation above, and the nightly replay is the catch-up.
  let departure = null;
  if (!parsedBounce && loss === 'departed') {
    try {
      const { handleDeparture } = require('./departureRecovery');
      departure = await handleDeparture(sb, {
        company_id: companyId, sender, subject, body: body_text, gmail_thread_id,
        received_at, now: new Date(nowIso),
      });
      if (!departure.handled && !departure.already) {
        // Nothing could be worked out (which contact left, for instance). The
        // pre-recovery behaviour is still the right floor: surface the company
        // rather than let it go quiet.
        await sb.from('b2b_companies').update({ contact_unknown: true, updated_at: nowIso }).eq('id', companyId);
      }
    } catch (err) {
      console.warn(`[correlate] departure recovery failed on ${companyId}: ${err.message}`);
      departure = { handled: false, reason: `error: ${err.message}` };
    }
  }

  // 5. Thank-you closer: a human reply that is pure courtesy ("Thanks so
  // much!") concludes the conversation — close the thread the way the operator
  // would, so it never surfaces as Tier-1 "waiting on us". The companion of the
  // born-closed rule above: that one handles machine mail at thread creation,
  // this one handles human sign-offs mid-thread. The idempotent message insert
  // is the claim — only the worker that actually inserted the message runs the
  // classifier, so Pub/Sub redelivery cannot double-spend it. Fail-soft: any
  // error leaves the thread open, which is the status quo.
  let thankyou_closed = false;
  if (!duplicate && !inboundType) {
    try {
      const { maybeCloseThankYou } = require('./thankYouCloser');
      const closed = await maybeCloseThankYou(sb, { thread_id: threadId, inboundType, threadWasNew });
      thankyou_closed = closed.closed;
    } catch (err) {
      console.warn(`[correlate] thank-you closer skipped on thread ${threadId}: ${err.message}`);
    }
  }

  // 6. Gmail read state. Machine mail the engine just consumed (a bounce is
  // already queue work, an RSVP already sits on the meeting row, an
  // out-of-office asks nothing) and a thread the closer just concluded need no
  // eyes in the inbox; a person's reply keeps its bold. One verdict function
  // shared with the send tool and the nightly sweep — see readState.js.
  // Fail-soft inside settleThreadReadState: a Gmail hiccup never undoes the
  // correlation above.
  let read_state = null;
  if (gmail_thread_id && (inboundType || thankyou_closed)) {
    const { settleThreadReadState } = require('./readState');
    read_state = await settleThreadReadState({ sb, gmail_thread_id });
  }

  return {
    matched: true,
    company_id: companyId,
    thread_id: threadId,
    duplicate,
    // null = a person wrote; anything else is machine mail (see classifyInbound).
    inbound_type: inboundType,
    contact_loss: loss,
    bounce,
    departure,
    thankyou_closed,
    reopened,
    read_state,
    looks_like_order: looksLikeOrder(body_text || ''),
  };
}

module.exports = {
  correlateInbound,
  detectContactLoss,
  looksLikeOrder,
  detectAutoReply,
  detectCalendarNotice,
  classifyInbound,
  NON_REPLY_INBOUND_TYPES,
};
