/**
 * replyCorrelation.js — Trigger 2: inbound email → B2B relationship state.
 *
 * Called from the Gmail push handler (and the nightly sync as catch-up) for
 * each new inbound message. If the sender belongs to a known B2B contact or a
 * company's general_email, the message is recorded on the company's thread
 * (idempotent on gmail_message_id — Pub/Sub is at-least-once) and the company
 * surfaces as Tier 1 in the queue (computed from lastInbound > lastOutbound).
 *
 * Also implements the design's contact-change detection: hard bounces and
 * "no longer with" auto-replies flag contact_unknown, which pauses cadence
 * (cadence.companyEligible) until the operator confirms a new contact.
 */
const { getSupabaseClient } = require('../../shared/supabaseClient');
const { identifyingDomain, emailDomain } = require('./emailDomains');
const { parseBounce, handleBounce } = require('./bounceRecovery');

/** Bounce / departure detection (Design #3 contact-change flow). Pure. */
function detectContactLoss({ subject = '', body = '', from = '' } = {}) {
  const s = `${subject}\n${body}`.slice(0, 2000);
  if (/mailer-daemon|postmaster@/i.test(from) && /(delivery|undeliver|not be delivered|address not found|550|user unknown)/i.test(s)) {
    return 'hard_bounce';
  }
  if (/(no longer (with|at|works)|has left the (org|company|team)|is no longer employed|please (contact|reach out to) .{0,60} going forward)/i.test(s)) {
    return 'departed';
  }
  return null;
}

/** Heuristic: does an inbound look like a wholesale order? Pure. */
function looksLikeOrder(body = '') {
  const lines = body.split('\n');
  let itemish = 0;
  for (const l of lines) {
    if (/^\s*\d+\s*[xX×]?\s+[A-Za-z]/.test(l) && /(size|S|M|L|XL|\d{1,2})/i.test(l)) itemish++;
  }
  return itemish >= 2 || /\b(purchase order|PO\s*#|wholesale order|order form)\b/i.test(body);
}

/**
 * Conservative auto-responder detection (content layer — the gmail intake's
 * is_auto_reply and protocol headers are the first line; this catches what
 * they miss, e.g. Mermaids' "we'll be back to you within 2 business days").
 * Deliberately narrow patterns: a mislabel in either direction is visible and
 * recoverable (the message stays in history either way), so favor precision.
 * Pure.
 */
const AUTO_REPLY_PATTERN = /\b(automatic reply|auto[- ]?repl(y|ied)|out of (the )?office|this (inbox|mailbox) is not monitored|do not reply to this (e-?mail|message)|we('|’)?ll (get|be) back to you within [^.\n]{0,30}(business |working )?days)\b/i;

function detectAutoReply({ subject, body }) {
  const s = String(subject || '');
  const b = String(body || '');
  // A subject that OPENS with "Re:" is a person writing into an existing
  // thread — including into an auto-responder's own thread, which Gmail gives
  // its own subject ("Out of Office Re: ..."). Judging that on the subject
  // would file their reply as machine-generated, and since such a thread is
  // now born closed, the reply would be invisible twice over. So judge it on
  // the body alone: a genuine responder announces itself there too. Same
  // reasoning detectCalendarNotice already applies to "Re: Accepted: ...".
  if (/^\s*re:\s*/i.test(s)) return AUTO_REPLY_PATTERN.test(b);
  return AUTO_REPLY_PATTERN.test(`${s}\n${b}`);
}

/**
 * Calendar notifications: an RSVP, an invitation, an update, a cancellation.
 *
 * These are generated by calendar software but sent FROM the contact's own
 * address, so every layer above treats them as that person writing to us. An
 * acceptance in particular lands AFTER our last outbound (we send the invite,
 * they accept), which is exactly the Tier-1 condition — so booking a call puts
 * the company straight back in the queue as "replied, waiting on us" at the
 * moment the scheduling is finished and there is least to say. Lumenus was
 * queued by an acceptance of a call that was already booked, and the only way
 * to clear it was to close the notification by hand.
 *
 * Held to the same precision-first bar as detectAutoReply: the message stays in
 * history either way, but a false positive here silences a real human.
 * Pure.
 */
const CALENDAR_SUBJECT = /^\s*(accepted|declined|tentative|invitation|updated invitation|new event|updated event|cancell?ed event|canceled event):\s+\S/i;
const CALENDAR_RSVP = /^\s*(accepted|declined|tentative):\s+\S/i;
const CALENDAR_BODY = /(calendar\.google\.com\/calendar\/event|has (accepted|declined|tentatively accepted) this invitation|this event has been (updated|cancell?ed|canceled)|BEGIN:VCALENDAR)/i;

function detectCalendarNotice({ subject, body } = {}) {
  const s = String(subject || '');
  // No `Re:` tolerance anywhere here, deliberately. A generated notice never
  // carries one, and Gmail threads on subject — so a human replying inside the
  // notification's thread arrives as "Re: Accepted: …" and must stay a reply.
  if (!CALENDAR_SUBJECT.test(s)) return false;
  // An RSVP subject is unambiguous: nobody writes "Accepted: <thing>" as an
  // entire subject line. It also has to stand on the subject alone — the RSVP
  // is the one that reaches correlateInbound with an EMPTY body over Pub/Sub,
  // so requiring corroboration would miss the case this exists for.
  if (CALENDAR_RSVP.test(s)) return true;
  // "Invitation: Pride Picnic 2026" is a subject an org could plausibly write
  // by hand, so this half has to be corroborated by the body.
  const b = String(body || '').trim();
  return !b || CALENDAR_BODY.test(b);
}

/**
 * Inbound message_types that are on the record but are not a person waiting on
 * a reply. queueContext skips these when deriving lastInboundAt, which is what
 * keeps them out of Tier 1.
 */
// A delivery failure joins these for the same reason a calendar acceptance
// does: it is evidence ABOUT a message, never a human writing back. The DSN is
// kept on the thread so the panel can show why a check-in got no answer, but
// counting it as a reply would put the company at Tier 1 as though they had
// replied — which is exactly what the pre-fix panel did.
const NON_REPLY_INBOUND_TYPES = new Set(['auto_reply', 'calendar_notice', 'bounce']);

/** Classify an inbound message. Returns a message_type or null. Pure. */
function classifyInbound({ subject, body, from } = {}) {
  if (detectContactLoss({ subject, body, from }) === 'hard_bounce') return 'bounce';
  if (detectCalendarNotice({ subject, body })) return 'calendar_notice';
  if (detectAutoReply({ subject, body })) return 'auto_reply';
  return null;
}

/**
 * Correlate one inbound message. Returns
 * { matched, company_id?, thread_id?, duplicate?, contact_loss?, looks_like_order?, auto_reply? }.
 */
async function correlateInbound(msg) {
  const { gmail_message_id, gmail_thread_id, from_email, to_email, cc_email, subject, body_text, received_at } = msg;
  if (!gmail_message_id || !from_email) return { matched: false, reason: 'missing ids' };
  const sb = getSupabaseClient();
  const sender = String(from_email).toLowerCase().replace(/^.*</, '').replace(/>.*$/, '').trim();

  // 1. Sender → company
  let companyId = null;
  const { data: contact } = await sb.from('b2b_contacts')
    .select('company_id').eq('email', sender).maybeSingle();
  if (contact?.company_id) companyId = contact.company_id;
  if (!companyId) {
    const { data: byGeneral } = await sb.from('b2b_companies')
      .select('id').eq('general_email', sender).maybeSingle();
    if (byGeneral?.id) companyId = byGeneral.id;
  }

  // 1b. Sender DOMAIN → company. Exact-address matching alone silently drops
  // mail from a colleague of the person we have on file, and that is not an
  // edge case: 16 of 45 uncorrelated threads were companies we already knew,
  // writing from an address that simply was not registered. Four of them then
  // sat in the queue reading "no prior outbound" while their conversation ran
  // in Gmail. Same shape as the partner whose survey gave us programs@ while
  // every real thread was with mg@.
  //
  // Only an identifying domain counts (see emailDomains): a gmail.com sender
  // would otherwise attach to whichever company happened to have a gmail
  // contact. When this path matches, register the address so the exact-match
  // above wins next time and the company stops depending on the fallback.
  let matchedByDomain = false;
  if (!companyId) {
    const domain = identifyingDomain(sender);
    if (domain) {
      const { data: byWebsite } = await sb.from('b2b_companies')
        .select('id, website, relationship_state').ilike('website', `%${domain}%`);
      const site = (byWebsite || []).find(c => identifyingDomain(c.website) === domain
        && c.relationship_state !== 'lost');
      if (site) companyId = site.id;

      if (!companyId) {
        const { data: peers } = await sb.from('b2b_contacts')
          .select('company_id, email').ilike('email', `%@${domain}`);
        const peer = (peers || []).find(c => emailDomain(c.email) === domain && c.company_id);
        if (peer) companyId = peer.company_id;
      }
      matchedByDomain = !!companyId;
    }
  }

  // Bounce case: the sender is mailer-daemon, so it tells us nothing about who
  // this is about. The DSN's Final-Recipient does — and it is a far sharper key
  // than the thread, which Gmail shares between orgs: naming the failed address
  // says exactly whose contact died, where an ambiguous thread previously had to
  // give up rather than risk pausing the wrong org's cadence.
  const loss = detectContactLoss({ subject, body: body_text, from: sender });
  const parsedBounce = loss === 'hard_bounce'
    ? parseBounce({ subject, body: body_text, from: sender }) : null;
  if (!companyId && parsedBounce) {
    for (const f of parsedBounce.failures) {
      const { data: c } = await sb.from('b2b_contacts')
        .select('company_id').eq('email', f.address).maybeSingle();
      if (c?.company_id) { companyId = c.company_id; break; }
      const { data: m } = await sb.from('b2b_messages')
        .select('company_id').eq('to_email', f.address).eq('direction', 'outbound')
        .order('sent_at', { ascending: false }).limit(1);
      if (m?.[0]?.company_id) { companyId = m[0].company_id; break; }
    }
  }
  if (!companyId && loss === 'hard_bounce' && gmail_thread_id) {
    // Fallback for a DSN we could not read a recipient out of. Still refuses to
    // guess on a shared thread: marking the wrong org's contact dead pauses a
    // relationship that was perfectly healthy.
    const { data: threads } = await sb.from('b2b_threads')
      .select('company_id').eq('gmail_thread_id', gmail_thread_id);
    const owners = [...new Set((threads || []).map(t => t.company_id))];
    if (owners.length === 1) companyId = owners[0];
  }
  if (!companyId) {
    // A bounce we cannot attribute is a dead address we will keep writing to.
    if (loss === 'hard_bounce') {
      console.warn(`[correlate] unattributed bounce ${gmail_message_id}: ${(parsedBounce?.failures || []).map(f => f.address).join(', ') || 'no recipient parsed'}`);
    }
    return { matched: false, contact_loss: loss || undefined };
  }

  // 2. Thread: match by (company, gmail_thread_id), else create.
  //
  // Scoped by company, not by gmail_thread_id alone. Gmail threads on subject, so
  // one conversation regularly holds two orgs — an unscoped lookup found the OTHER
  // company's row and filed this message under their relationship. That is how 105
  // messages ended up mis-parented. A company now only ever matches its own row.
  const inboundType = classifyInbound({ subject, body: body_text, from: sender });

  let threadId = null;
  const { data: thread } = await sb.from('b2b_threads')
    .select('id').eq('gmail_thread_id', gmail_thread_id).eq('company_id', companyId).maybeSingle();
  if (thread) {
    threadId = thread.id;
  } else {
    // A thread whose FIRST message is machine-generated is born concluded.
    // Gmail threads on subject, so an out-of-office ("Out of office RE: ...")
    // opens a thread of its own, and there is nothing for a person to do with
    // it. discoveredThreadStatus has always applied this rule on the Gmail
    // discovery path; live Pub/Sub inbound never did, so every auto-reply that
    // arrived in real time left an open thread to be closed by hand.
    //
    // Only ever at CREATION. An auto-reply landing inside a live conversation
    // must not close it — they are still mid-thread with us, and the responder
    // says nothing about that.
    const bornClosed = NON_REPLY_INBOUND_TYPES.has(inboundType);
    const { data: created, error } = await sb.from('b2b_threads').insert({
      company_id: companyId, thread_type: 'other',
      subject: (subject || '').slice(0, 300), gmail_thread_id,
      last_message_at: received_at || new Date().toISOString(),
      ...(bornClosed ? { status: 'closed' } : {}),
    }).select('id').single();
    if (error) {
      // unique race: another worker created it — refetch
      const { data: again } = await sb.from('b2b_threads')
        .select('id').eq('gmail_thread_id', gmail_thread_id).eq('company_id', companyId).maybeSingle();
      if (!again) throw new Error(`thread create: ${error.message}`);
      threadId = again.id;
    } else {
      threadId = created.id;
    }
  }

  // 3. Idempotent message insert (UNIQUE gmail_message_id). Auto-responders,
  // calendar notifications and delivery failures are kept for history but
  // labeled so they never create a Tier-1 "waiting on us" (queueContext skips
  // the types in NON_REPLY_INBOUND_TYPES). Keeping the DSN matters: without it
  // the panel shows a warm check-in going out and silence coming back, which is
  // exactly how two dead partner addresses stayed invisible.
  const { error: mErr } = await sb.from('b2b_messages').insert({
    thread_id: threadId, company_id: companyId, direction: 'inbound',
    message_type: inboundType,
    gmail_message_id, gmail_thread_id,
    from_email: sender, to_email: to_email || null, cc_email: cc_email || null,
    body_text: (body_text || '').slice(0, 20000),
    sent_at: received_at || new Date().toISOString(), source: 'pubsub',
  });
  let duplicate = false;
  if (mErr) {
    if (mErr.code !== '23505') throw new Error(`b2b_messages insert: ${mErr.message}`);
    // Already stored — which says nothing about whether its CONSEQUENCES were
    // applied. Returning here skipped bounce handling for exactly the messages
    // the replay exists to repair (it re-reads mail the push path already
    // inserted), and still reported a match, so a run that did nothing looked
    // like a run that worked. handleBounce is independently idempotent; let it
    // be the thing that decides whether there is work left.
    duplicate = true;
  }

  // 3b. Register an address we only reached via the domain fallback, so the
  // exact-address match handles it next time and resolveRecipient can see it.
  // Not primary: a colleague writing in does not displace the person we have
  // deliberately been corresponding with.
  if (matchedByDomain) {
    const { error: cErr } = await sb.from('b2b_contacts').upsert({
      id: sender, email: sender, company_id: companyId,
      is_primary: false, is_active: true, source: 'inbound_domain_match',
      notes: `Auto-added ${new Date().toISOString().slice(0, 10)}: wrote in from a domain already on this company.`,
    }, { onConflict: 'id', ignoreDuplicates: true });
    if (cErr) console.warn(`[correlate] contact auto-add ${sender}: ${cErr.message}`);
  }

  // 4. State updates
  const nowIso = new Date().toISOString();
  await sb.from('b2b_threads').update({ last_message_at: received_at || nowIso }).eq('id', threadId);
  // A hard bounce knows WHICH address died, so it can do the specific thing:
  // retire that contact, revive the approved text against a live one, and undo
  // the cadence date the failed send bought. Flagging the whole company
  // `contact_unknown` here instead would pause it entirely and render nowhere —
  // muting a partner we can still reach at another address.
  let bounce = null;
  if (parsedBounce) {
    for (const failure of parsedBounce.failures) {
      if (!failure.permanent) continue;
      bounce = await handleBounce(sb, { failure, gmail_thread_id, now: new Date(nowIso) });
    }
    if (parsedBounce.unparsed) {
      console.warn(`[correlate] unreadable DSN ${gmail_message_id} on company ${companyId}`);
    }
  } else if (loss === 'departed') {
    // A human telling us someone left names a successor we cannot parse
    // reliably. The operator resolves it with update_contact; until then the
    // company surfaces via the queue's "no working address" branch rather than
    // going quiet.
    await sb.from('b2b_companies').update({ contact_unknown: true, updated_at: nowIso }).eq('id', companyId);
  }

  return {
    matched: true,
    company_id: companyId,
    thread_id: threadId,
    duplicate,
    contact_loss: loss,
    bounce,
    looks_like_order: looksLikeOrder(body_text || ''),
  };
}

module.exports = {
  correlateInbound,
  detectContactLoss,
  looksLikeOrder,
  detectAutoReply,
  detectCalendarNotice,
  classifyInbound,
  NON_REPLY_INBOUND_TYPES,
};
