/**
 * triage.js — the vetting decision on a company, before any drafting happens.
 *
 * Tier 4 (prospect first-touch) requires `vetted_at`. That gate exists because
 * turning the tier on makes ~200 imported rows eligible at once, and they are
 * not equally ready: 23 donation-form orgs told us their size ranges and named
 * a contact, while ~120 CenterLink rows are a name slug and an email until the
 * research pass enriches them. Admission is deliberate, cohort by cohort.
 *
 * Three decisions, deliberately small:
 *   keep   → vetted_at = now         (admit to the queue)
 *   drop   → relationship_state=lost (never surfaces again; reason recorded)
 *   snooze → snoozed_until = date    (out of the queue until then)
 *
 * No draft is generated by any of them — the whole point is to clear a cohort
 * without paying for a draft per row.
 */

/**
 * Compute the update for one triage decision. Pure, so the tool, the bulk
 * script and the (future) panel all produce identical writes.
 *
 * @param action  'keep' | 'drop' | 'snooze'
 * @param opts    { reason, until (snooze only, YYYY-MM-DD), now }
 * @returns the b2b_companies patch
 */
function computeTriage(action, { reason = null, until = null, now = new Date() } = {}) {
  switch (action) {
    case 'keep':
      // Reason is optional on keep — "yes, this one is fine" needs no essay.
      return { vetted_at: now.toISOString(), triage_reason: reason || null };
    case 'drop':
      if (!reason) throw new Error('drop requires a reason — an unexplained lost row gets re-litigated later');
      return { relationship_state: 'lost', triage_reason: reason, vetted_at: null };
    case 'snooze': {
      if (!until) throw new Error('snooze requires an until date (YYYY-MM-DD)');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(until)) throw new Error(`snooze until must be YYYY-MM-DD, got '${until}'`);
      if (new Date(`${until}T00:00:00Z`) <= now) throw new Error(`snooze until must be in the future, got '${until}'`);
      return { snoozed_until: until, triage_reason: reason || null };
    }
    default:
      throw new Error(`unknown triage action '${action}' — expected keep, drop or snooze`);
  }
}

/** Apply a triage decision to one company. */
async function triageCompany(sb, { company_id, action, reason, until, now = new Date() } = {}) {
  if (!company_id) throw new Error('company_id required');
  const { data: company, error } = await sb.from('b2b_companies')
    .select('id, name, relationship_state').eq('id', company_id).maybeSingle();
  if (error) throw new Error(error.message);
  if (!company) throw new Error(`company '${company_id}' not found`);

  const patch = computeTriage(action, { reason, until, now });
  const { error: uErr } = await sb.from('b2b_companies')
    .update({ ...patch, updated_at: now.toISOString() }).eq('id', company_id);
  if (uErr) throw new Error(uErr.message);
  return { company_id, name: company.name, action, ...patch };
}

module.exports = { computeTriage, triageCompany };
