/**
 * triage.js — the vetting decision on a company, before any drafting happens.
 *
 * Tier 4 (prospect first-touch) requires `vetted_at`. That gate exists because
 * turning the tier on makes ~200 imported rows eligible at once, and they are
 * not equally ready: 23 donation-form orgs told us their size ranges and named
 * a contact, while ~120 CenterLink rows are a name slug and an email until the
 * research pass enriches them. Admission is deliberate, cohort by cohort.
 *
 * The vetting decisions, deliberately small:
 *   keep   → vetted_at = now         (admit to the queue)
 *   drop   → relationship_state=lost (never surfaces again; reason recorded)
 *   snooze → snoozed_until = date    (out of the queue until then)
 *
 * And the dispositions on a company already in play, which share this path so
 * the panel and the console tool can never mean different things by them:
 *   pause  → indefinitely not worked  (ours to reverse; reason required)
 *   on_me  → Jamie has claimed it     (still live, just not in today's queue)
 *   resume → back in the queue        (lifts whichever of the three is set)
 *
 * No draft is generated by any of them — the whole point is to clear a cohort
 * without paying for a draft per row.
 */

/**
 * Compute the update for one triage decision. Pure, so the tool, the bulk
 * script and the (future) panel all produce identical writes.
 *
 * @param action  'keep' | 'drop' | 'snooze'
 * @param opts    { reason, until (snooze only, YYYY-MM-DD), now }
 * @returns the b2b_companies patch
 */
function computeTriage(action, { reason = null, until = null, now = new Date() } = {}) {
  switch (action) {
    case 'keep':
      // Reason is optional on keep — "yes, this one is fine" needs no essay.
      return { vetted_at: now.toISOString(), triage_reason: reason || null };
    case 'drop':
      if (!reason) throw new Error('drop requires a reason — an unexplained lost row gets re-litigated later');
      return { relationship_state: 'lost', triage_reason: reason, vetted_at: null };
    case 'snooze': {
      if (!until) throw new Error('snooze requires an until date (YYYY-MM-DD)');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(until)) throw new Error(`snooze until must be YYYY-MM-DD, got '${until}'`);
      if (new Date(`${until}T00:00:00Z`) <= now) throw new Error(`snooze until must be in the future, got '${until}'`);
      // snoozed_at, not just snoozed_until: the queue needs to know WHEN the
      // decision was made to tell an already-stale "waiting on us" apart from a
      // reply that lands during the snooze.
      return { snoozed_until: until, snoozed_at: now.toISOString(), triage_reason: reason || null };
    }
    case 'pause': {
      // Indefinite by design — the whole reason snooze does not fit is that
      // "not working Canadian retailers this year" has no date attached, and
      // inventing one produces a queue item on a day nobody chose.
      if (!reason) throw new Error('pause requires a reason — in six months "why is this paused?" is the only question that matters');
      return { outreach_paused_at: now.toISOString(), outreach_paused_reason: reason };
    }
    case 'on_me': {
      // "I owe them an answer, just not this minute." Unlike pause and snooze,
      // the work is still live — it moves to a list Jamie holds instead of
      // leaving the system. No reason is required: the decision is made in a
      // second while working the queue, and demanding a sentence for it would
      // just mean leaving the row in the queue instead, which is the whole
      // problem this exists to solve.
      return { on_me_at: now.toISOString(), on_me_note: reason || null };
    }
    case 'resume':
      // Clears ALL of them, which is what the button means wherever it appears.
      // It used to null only the pause columns, so the "Resume now" rendered
      // beside a live snooze was a no-op — it reported success and the company
      // stayed snoozed. One action for "put this back in the queue" cannot know
      // which flavour the operator is looking at, so it lifts whatever is there.
      return {
        outreach_paused_at: null, outreach_paused_reason: null,
        snoozed_until: null, snoozed_at: null,
        on_me_at: null, on_me_note: null,
      };
    default:
      throw new Error(`unknown triage action '${action}' — expected keep, drop, snooze, pause, on_me or resume`);
  }
}

/** Apply a triage decision to one company. */
async function triageCompany(sb, { company_id, action, reason, until, now = new Date() } = {}) {
  if (!company_id) throw new Error('company_id required');
  const { data: company, error } = await sb.from('b2b_companies')
    .select('id, name, relationship_state').eq('id', company_id).maybeSingle();
  if (error) throw new Error(error.message);
  if (!company) throw new Error(`company '${company_id}' not found`);

  const patch = computeTriage(action, { reason, until, now });
  const { error: uErr } = await sb.from('b2b_companies')
    .update({ ...patch, updated_at: now.toISOString() }).eq('id', company_id);
  if (uErr) throw new Error(uErr.message);

  // A pending draft is a chase waiting to be sent, so deciding not to chase has
  // to clear it. Leaving it behind does not merely look untidy: the panel merges
  // any company holding a pending draft back INTO the queue, carrying the tier
  // and reason frozen on the draft row, so a paused company reappeared at its
  // old tier with a stale "now due" explanation. Superseded rather than
  // dismissed, so the advisor's text survives as training signal.
  //
  // `on_me` is deliberately absent from that list: there the work is still
  // happening, and the draft is the thing you want in front of you when you pick
  // it back up. Throwing it away would mean paying for a second Opus call to
  // recreate what you had already read. The merge exclusion that keeps a paused
  // company out of the queue is what stops that surviving draft dragging the row
  // back in — see mergePendingDraftEntries.
  let draftsCleared = 0;
  if (action === 'pause' || action === 'snooze' || action === 'drop') {
    const { data, error: dErr } = await sb.from('b2b_drafts')
      .update({ status: 'superseded' })
      .eq('company_id', company_id).eq('status', 'pending').select('id');
    if (dErr) throw new Error(`clear pending drafts: ${dErr.message}`);
    draftsCleared = (data || []).length;
  }

  return { company_id, name: company.name, action, drafts_cleared: draftsCleared, ...patch };
}

module.exports = { computeTriage, triageCompany };
